server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soccer_db
    username: root
    password: mysql1530
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations:
      classpath: db/migration
    baseline-on-migration: true